--- #deploy file to env

- hosts: dev
  become: yes
  user: att
  connection: ssh
  gather_facts: yes

  tasks:    
    - name: deploy-tomcat
      ansible.builtin.copy:
        src: "{{ source }}"
        dest: "{{ destin }}"
        mode: 755
      notify:
      - restart
      
    - name: start-docker
      ansible.builtin.service:
        name: docker
        state: started
      notify:
        - create-docker-image
        - create-docker-conatiner

  handlers:
    - name: create-docker-image
      ansible.builtin.command:
        cmd: docker build -it arp-tomcat:1 .         
          
    - name: create-docker-container
      ansible.builtin.command:
       cmd: docker run -itdp "80:8080" arp-tomcat:1
       
    - name: restart
      ansible.builtin.command:
        cmd: /home/att/server/apache-tomcat-9.0.65/bin/startup.sh


  vars:
    source: /home/att/project/target/onlinebookstore-2.war
    destin: /home/att/server/apache-tomcat-9.0.65/webapps/
