--- #deploy file to env

- hosts: dev
  become: yes
  user: ansible
  connection: ssh
  gather_facts: yes

  tasks:
    - name: copy-to-node
      ansible.builtin.copy:
        src: "{{ source }}"
        dest: "{{ destin }}"
        mode: 755
    
    - name: deploy-tomcat
      ansible.builtin.copy:
        src: "{{ destin }}"
        dest: /root/server/apache*tomcat/webapps/ 
      ansible.builtin.command:
        cmd: /root/apa*tomcat*/bin/startup.sh

    - name: start-docker
      ansible.builtin.service:
        name: docker
        state: start
      notify:
        - create-docker-image
        - create-docker-conatiner

  handlers:
    - name: create-docker-image
      ansible.builtin.command:
        cmd: docker build -it arp-tomcat:1 .         
          
    - name: create-docker-container
      ansible.builtin.command:
       cmd: docker run -itdp "80:8080" arp-tomcat:1

  vars:
    source: /root/project/onlinebookstore-2.war
    destin: /home/ansible
